from django.conf.urls import patterns,url,include

urlpatterns = patterns('demo.views',    
    url('',include('social_auth.urls')),
    (r'^$','main'),
    (r'^socialize/',include('socialize.urls')),
    (r'^project','project_form'),
    (r'^events/(?P<eventid>\d+)$','eventview'),
    (r'^projects/(?P<projectid>\d+)$','project'),
    (r'^promoted','promoted'),
    (r'^eventid','eventid'),
    (r'^projectform','project_main'),
    (r'^backers','backers'),
    (r'^movements','movements'),
    (r'^promote','promote'),
    (r'^linkproj','link'),
    (r'^movement','movement'),
    (r'^pledge','pledge'),
    (r'^grab','grab'),
    (r'^eventimage','event_image'),
    (r'^event','eventview'),
    (r'^enroll','enroll'),
    (r'^calendar','event'),
) 
