# Generated by Django 5.1.6 on 2025-03-04 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('socialize', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPubObject',
            fields=[
                (
                    'id',
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ('type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                (
                    'actor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPubActivity',
            fields=[
                (
                    'id',
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ('type', models.CharField(max_length=50)),
                ('published', models.DateTimeField(auto_now_add=True)),
                (
                    'actor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'object',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='socialize.activitypubobject',
                    ),
                ),
            ],
        ),
    ]
