# Generated by Django 5.1.6 on 2025-03-04 11:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('socialize', '0002_activitypubobject_activitypubactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('activity_type', models.CharField(max_length=50)),
                ('object_data', models.JSONField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('username', models.CharField(max_length=100, unique=True)),
                (
                    'display_name',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ('inbox', models.URLField(blank=True, null=True)),
                ('outbox', models.URLField(blank=True, null=True)),
                ('actor_type', models.CharField(default='Person', max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('bio', models.TextField(default='', max_length=140)),
                ('title', models.CharField(default='', max_length=50)),
                ('birthdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('object_type', models.CharField(default='Note', max_length=50)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                (
                    'actor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Vault',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('access_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'actor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='socialize.actor',
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='activitypubactivity',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='activitypubactivity',
            name='object',
        ),
        migrations.RemoveField(
            model_name='activitypubobject',
            name='actor',
        ),
        migrations.DeleteModel(
            name='Followed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='activity',
            name='actor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='socialize.actor'
            ),
        ),
        migrations.DeleteModel(
            name='ActivityPubActivity',
        ),
        migrations.DeleteModel(
            name='ActivityPubObject',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
