# Generated by Django 5.1.6 on 2025-03-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('socialize', '0004_alter_object_actor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vault',
            options={'verbose_name': 'Vault', 'verbose_name_plural': 'Vaults'},
        ),
        migrations.RemoveField(
            model_name='vault',
            name='access_key',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='actor',
            name='public_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vault',
            name='private_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
