# Generated by Django 5.1.6 on 2025-06-26 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0006_actor_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='username',
        ),
        migrations.AddField(
            model_name='actor',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 26, 15, 20, 10, 952372, tzinfo=datetime.timezone.utc)),
        ),
    ]
