# Generated by Django 5.2.18 on 2026-10-09 16:22

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialize", "0007_remove_actor_username_actor_score_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="activity_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="actor",
            name="actor_url",
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="actor",
            name="domain",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="actor",
            name="followers_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="actor",
            name="following_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="actor",
            name="shared_inbox",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="actor",
            name="username",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="object",
            name="attachment",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="object",
            name="object_url",
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="object",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="actor",
            name="bio",
            field=models.TextField(blank=True, default="", max_length=140),
        ),
        migrations.AlterField(
            model_name="actor",
            name="inbox",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="actor",
            name="outbox",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="actor",
            name="public_key",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="actor",
            name="title",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="actor",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="token",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 10, 9, 17, 22, 34, 934004, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("accepted", models.BooleanField(default=True)),
                ("activity_id", models.URLField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_set",
                        to="socialize.actor",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers_set",
                        to="socialize.actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Follow",
                "verbose_name_plural": "Follows",
                "unique_together": {("actor", "target")},
            },
        ),
    ]
