# Generated by Django 5.1.6 on 2025-03-04 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0003_activity_actor_object_vault_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialize.actor'),
        ),
    ]
